# Generated by Django 4.1.6 on 2023-03-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='type',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
